language: node_js
node_js: 
  - stable

deploy:
  edge: true
  provider: cloudfoundry
  username: devanand.madhavan@verizon.com
  password: tFgC+xlCV/d2pGbgCXvwtIT10Ey6obpwOGlLFMllq/fDFfP2W3BT1zDd7p0o+XXLyobCc/J9TTdFPMvZj7/zKUxJyXy+QDDnc5JsUY628NQrbqduH+vVrIYuA9Op9lQjuZa4XiB2YhTBTejzqIoYAvnlTaEb/4o1CYH8Gradu15FI5NmjYHE1OxfnuuQk3k65nsSeHibPfaIlSMtLps6XNOhlJKwYxyZNH5iDtGPguf0YWZQoSZgjKpRmHk7Sa8PjSM55oYbULtg8F68f7ZTvoZew1bHNue2IXHxhT4/41VJym/47zrF0GzyvpitNv8kpxm4tTF9pDznxLwCtymowfZ+WuTEDV9GqHphnh9dV5bv5jyGFTLgeCNfDrI4l9rDYqJWJSAsrgHA8d2XizrECMxYZI/1Urb2/1JDAIwpVQKr4H4uBvl0r7K6NG69F4ArueDRcilXoe52tFKHuLV5r6fpFBpnWJpxc7QgQaj4fCjxBSloSsLfxqG7NOUljvrGDMCEw74OM5Em87lFUpFzA2+xd5aC8UBMqylTms3zJU+q56kxch9lPkHZzV+ksDY91DUenrCfe3Wdm8kySsBdVAsYfkmd5xfJskMhUQjP9zmyg3RI1m8oVHk94HzIqO81Lbph9RSC5UvLyWdJS5HhpoGOu6qekE4fS1ZalAaMsoY=
  api: https://api.run.pivotal.io
  organization: VzCF
  space: development